"use client"

import { useState, useEffect, useRef } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Sparkles, Loader2, AlertCircle, ArrowLeft, RefreshCw, ArrowRight } from "lucide-react"
import type { WebsiteContent } from "@/types/website"

type PageStatus = "loading" | "empty" | "generating" | "ready" | "error"

export default function GenerateContentPage() {
  const [content, setContent] = useState<WebsiteContent | null>(null)
  const [status, setStatus] = useState<PageStatus>("loading")
  const [error, setError] = useState("")
  const [saving, setSaving] = useState(false)
  const [_saved, setSaved] = useState(false)
  const [editingSection, setEditingSection] = useState<string | null>(null)
  const router = useRouter()

  const autoGeneratedRef = useRef(false)

  const handleGenerate = async () => {
    setStatus("generating")
    setError("")

    try {
      const res = await fetch("/api/generate-content", { method: "POST" })
      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || "Generation failed")
      }

      setContent(data.content)
      setStatus("ready")
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong")
      setStatus("error")
    }
  }

  useEffect(() => {
    async function fetchContent() {
      try {
        const res = await fetch("/api/generate-content")
        if (res.status === 404) {
          const urlParams = new URLSearchParams(window.location.search)
          if (urlParams.get("auto") === "true" && !autoGeneratedRef.current) {
            autoGeneratedRef.current = true
            handleGenerate()
          } else if (!autoGeneratedRef.current) {
            setStatus("empty")
          }
          return
        }
        if (!res.ok) throw new Error("Failed to load")
        const data = await res.json()
        setContent(data.content)
        setStatus("ready")
      } catch {
        setStatus("empty")
      }
    }
    fetchContent()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleSave = async () => {
    if (!content) return
    setSaving(true)
    setSaved(false)

    try {
      const res = await fetch("/api/generate-content", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      })
      if (!res.ok) throw new Error("Failed to save")
      
      // Redirect to choose templates
      router.push("/dashboard/templates")
    } catch {
      setError("Failed to save changes")
    } finally {
      setSaving(false)
    }
  }

  const updateHero = (field: string, value: string) => {
    if (!content) return
    setContent({
      ...content,
      hero: { ...content.hero, [field]: value },
    })
  }

  const updateAbout = (value: string) => {
    if (!content) return
    setContent({
      ...content,
      about: { ...content.about, content: value },
    })
  }

  const updateExperienceHighlight = (
    expIdx: number,
    hlIdx: number,
    value: string
  ) => {
    if (!content) return
    const updated = [...content.experience]
    const highlights = [...updated[expIdx].highlights]
    highlights[hlIdx] = value
    updated[expIdx] = { ...updated[expIdx], highlights }
    setContent({ ...content, experience: updated })
  }

  const updateContact = (field: string, value: string) => {
    if (!content) return
    setContent({
      ...content,
      contact: { ...content.contact, [field]: value },
    })
  }

  // Loading state
  if (status === "loading") {
    return (
      <div className="min-h-[calc(100vh-64px)] bg-background py-12">
        <div className="max-w-4xl mx-auto px-6">
          <div className="animate-pulse space-y-6">
            <div className="h-8 bg-border rounded w-1/3" />
            <div className="h-48 bg-card rounded-2xl border border-border" />
            <div className="h-32 bg-card rounded-2xl border border-border" />
          </div>
        </div>
      </div>
    )
  }

  // Empty state — no content yet
  if (status === "empty" || status === "error") {
    return (
      <div className="min-h-[calc(100vh-64px)] bg-background flex flex-col items-center justify-center py-20">
        <div className="max-w-md mx-auto px-6 text-center">
          <Link
            href="/dashboard"
            className="mb-12 inline-flex items-center gap-1.5 text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" /> Back to dashboard
          </Link>

          <div className="rounded-3xl border border-border bg-card p-10 shadow-[var(--shadow-xl)]">
            <div className="mx-auto mb-6 flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-to-br from-primary to-secondary text-white shadow-[var(--shadow-glow)]">
              <Sparkles className="h-9 w-9" />
            </div>
            <h1 className="mb-3 text-2xl font-bold text-foreground">Generate website content</h1>
            <p className="mb-8 text-sm leading-relaxed text-muted-foreground">
              Our AI will transform your LinkedIn profile into polished, professional website copy — ready to publish.
            </p>

            {error && (
              <div role="alert" className="mb-6 flex items-center gap-2 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-2.5 text-left text-sm font-medium text-red-500">
                <AlertCircle className="h-4 w-4 flex-none" /> {error}
              </div>
            )}

            <button
              onClick={handleGenerate}
              className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-8 py-3.5 font-bold text-primary-foreground shadow-[var(--shadow-glow)] transition-all hover:-translate-y-0.5 hover:bg-primary-hover"
            >
              <Sparkles className="h-4 w-4" /> Generate with AI
            </button>
            <p className="mt-4 text-xs font-medium text-muted-foreground">Takes about 10 seconds</p>
          </div>
        </div>
      </div>
    )
  }

  // Generating state
  if (status === "generating") {
    return (
      <div className="min-h-[calc(100vh-64px)] bg-background flex flex-col items-center justify-center py-20">
        <div className="max-w-md mx-auto px-6 text-center">
          <div className="flex flex-col items-center rounded-3xl border border-border bg-card p-12 shadow-[var(--shadow-xl)]">
            <div className="mb-6 flex h-20 w-20 items-center justify-center rounded-2xl bg-primary/10 text-primary">
              <Loader2 className="h-10 w-10 animate-spin" />
            </div>
            <h2 className="mb-3 text-xl font-bold text-foreground">Crafting your content…</h2>
            <p className="text-sm text-muted-foreground mb-8">
              Analyzing your LinkedIn profile and writing professional website copy.
            </p>
            <div className="flex justify-center gap-2">
              {[0, 1, 2].map((i) => (
                <div
                  key={i}
                  className="w-2.5 h-2.5 rounded-full bg-primary animate-bounce"
                  style={{ animationDelay: `${i * 0.15}s` }}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    )
  }

  // Ready state — show generated content
  if (!content) return null

  return (
    <div className="min-h-[calc(100vh-64px)] bg-background">
      <div className="max-w-4xl mx-auto px-6 py-12 pb-32">
        <Link
          href="/dashboard"
          className="mb-8 inline-flex items-center gap-1.5 text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" /> Back to dashboard
        </Link>

        <div className="mb-8 flex items-start justify-between gap-4">
          <div>
            <h1 className="font-[var(--font-display)] text-3xl font-extrabold tracking-tight text-foreground">Review content</h1>
            <p className="mt-2 text-sm text-muted-foreground">Click any section to edit manually, or save to pick a template.</p>
          </div>
          <button
            onClick={handleGenerate}
            className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-semibold text-foreground shadow-sm transition-colors hover:border-primary/50 hover:bg-primary/5"
          >
            <RefreshCw className="h-4 w-4" /> Regenerate
          </button>
        </div>

        {error && (
          <div role="alert" className="mb-6 flex items-center gap-2 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-2.5 text-sm font-medium text-red-500">
            <AlertCircle className="h-4 w-4 flex-none" /> {error}
          </div>
        )}

        {/* Hero Section Preview */}
        <section
          className={`mb-6 rounded-2xl overflow-hidden cursor-pointer bg-card border transition-all duration-200 shadow-sm ${
            editingSection === "hero"
              ? "border-primary ring-1 ring-primary"
              : "border-border hover:border-primary/50"
          }`}
          onClick={() => setEditingSection(editingSection === "hero" ? null : "hero")}
        >
          <div className="p-10 text-center">
            {editingSection === "hero" ? (
              <div className="space-y-4 max-w-lg mx-auto" onClick={(e) => e.stopPropagation()}>
                <div>
                  <label className="block text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2 text-left">Name</label>
                  <input
                    type="text"
                    value={content.hero.name}
                    onChange={(e) => updateHero("name", e.target.value)}
                    className="w-full text-center text-3xl font-bold bg-background border border-border rounded-lg px-4 py-3 focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2 text-left">Tagline</label>
                  <input
                    type="text"
                    value={content.hero.tagline}
                    onChange={(e) => updateHero("tagline", e.target.value)}
                    className="w-full text-center text-lg bg-background border border-border rounded-lg px-4 py-3 focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2 text-left">Button Text</label>
                  <input
                    type="text"
                    value={content.hero.ctaText}
                    onChange={(e) => updateHero("ctaText", e.target.value)}
                    className="w-full text-center text-sm bg-background border border-border rounded-lg px-4 py-3 focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors"
                  />
                </div>
              </div>
            ) : (
              <>
                <h2 className="text-3xl font-extrabold text-foreground mb-3">{content.hero.name}</h2>
                <p className="text-lg text-muted-foreground mb-8 font-medium">{content.hero.tagline}</p>
                <span className="inline-block px-8 py-3 rounded-xl bg-primary text-primary-foreground font-bold text-sm shadow-md shadow-primary/20">
                  {content.hero.ctaText}
                </span>
              </>
            )}
          </div>
          <div className="bg-muted px-6 py-3 flex items-center justify-between border-t border-border">
            <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Hero Section</span>
            <span className="text-xs font-medium text-primary bg-primary/10 px-2 py-1 rounded">Click to {editingSection === "hero" ? "close" : "edit"}</span>
          </div>
        </section>

        {/* About Section Preview */}
        <section
          className={`mb-6 rounded-2xl overflow-hidden cursor-pointer bg-card border transition-all duration-200 shadow-sm ${
            editingSection === "about"
              ? "border-primary ring-1 ring-primary"
              : "border-border hover:border-primary/50"
          }`}
          onClick={() => setEditingSection(editingSection === "about" ? null : "about")}
        >
          <div className="p-8">
            <h3 className="text-xl font-bold text-foreground mb-4">{content.about.title}</h3>
            {editingSection === "about" ? (
              <div onClick={(e) => e.stopPropagation()}>
                <textarea
                  value={content.about.content}
                  onChange={(e) => updateAbout(e.target.value)}
                  rows={5}
                  className="w-full px-4 py-3 rounded-lg border border-border bg-background text-foreground text-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none resize-y transition-colors leading-relaxed"
                />
              </div>
            ) : (
              <p className="text-muted-foreground leading-relaxed whitespace-pre-line text-sm">
                {content.about.content}
              </p>
            )}
          </div>
          <div className="bg-muted px-6 py-3 flex items-center justify-between border-t border-border">
            <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">About Section</span>
            <span className="text-xs font-medium text-primary bg-primary/10 px-2 py-1 rounded">Click to {editingSection === "about" ? "close" : "edit"}</span>
          </div>
        </section>

        {/* Experience Section Preview */}
        <section
          className={`mb-6 rounded-2xl overflow-hidden cursor-pointer bg-card border transition-all duration-200 shadow-sm ${
            editingSection === "experience"
              ? "border-primary ring-1 ring-primary"
              : "border-border hover:border-primary/50"
          }`}
          onClick={() => setEditingSection(editingSection === "experience" ? null : "experience")}
        >
          <div className="p-8">
            <h3 className="text-xl font-bold text-foreground mb-8">Experience</h3>
            <div className="space-y-8">
              {content.experience.map((exp, i) => (
                <div key={i} className="relative pl-6 before:absolute before:left-0 before:top-2 before:bottom-0 before:w-px before:bg-border last:before:bottom-auto last:before:h-full">
                  <div className="absolute left-[-4px] top-2 w-2 h-2 rounded-full bg-primary ring-4 ring-card"></div>
                  <div className="flex items-start justify-between mb-2">
                    <div>
                      <h4 className="font-bold text-foreground">{exp.role}</h4>
                      <p className="text-sm font-medium text-primary">{exp.company}</p>
                    </div>
                    <span className="text-xs font-semibold text-muted-foreground bg-muted px-2 py-1 rounded ml-4 whitespace-nowrap">{exp.period}</span>
                  </div>
                  {editingSection === "experience" ? (
                    <div className="space-y-2 mt-4" onClick={(e) => e.stopPropagation()}>
                      {exp.highlights.map((hl, j) => (
                        <input
                          key={j}
                          type="text"
                          value={hl}
                          onChange={(e) =>
                            updateExperienceHighlight(i, j, e.target.value)
                          }
                          className="w-full px-3 py-2 text-sm rounded-lg border border-border bg-background text-foreground focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors"
                        />
                      ))}
                    </div>
                  ) : (
                    <ul className="space-y-2 mt-3">
                      {exp.highlights.map((hl, j) => (
                        <li key={j} className="text-sm text-muted-foreground flex gap-3">
                          <span className="text-primary/50 mt-1">•</span>
                          <span className="leading-relaxed">{hl}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}
            </div>
          </div>
          <div className="bg-muted px-6 py-3 flex items-center justify-between border-t border-border">
            <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Experience Section</span>
            <span className="text-xs font-medium text-primary bg-primary/10 px-2 py-1 rounded">Click to {editingSection === "experience" ? "close" : "edit"}</span>
          </div>
        </section>

        {/* Skills Section Preview */}
        <section
          className="mb-6 rounded-2xl overflow-hidden bg-card border border-border shadow-sm"
        >
          <div className="p-8">
            <h3 className="text-xl font-bold text-foreground mb-6">Skills</h3>
            <div className="grid gap-6 sm:grid-cols-2">
              {content.skills.categories.map((cat, i) => (
                <div key={i} className="bg-background rounded-xl p-5 border border-border">
                  <h4 className="text-xs font-bold text-foreground uppercase tracking-wider mb-4">
                    {cat.name}
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {cat.items.map((skill, j) => (
                      <span
                        key={j}
                        className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-card border border-border text-foreground shadow-sm"
                      >
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="bg-muted px-6 py-3 flex items-center justify-between border-t border-border">
            <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Skills Section</span>
          </div>
        </section>

        {/* Contact Section Preview */}
        <section
          className={`mb-6 rounded-2xl overflow-hidden cursor-pointer bg-card border transition-all duration-200 shadow-sm ${
            editingSection === "contact"
              ? "border-primary ring-1 ring-primary"
              : "border-border hover:border-primary/50"
          }`}
          onClick={() => setEditingSection(editingSection === "contact" ? null : "contact")}
        >
          <div className="p-8 text-center max-w-lg mx-auto">
            {editingSection === "contact" ? (
              <div className="space-y-4 text-left" onClick={(e) => e.stopPropagation()}>
                <div>
                  <label className="block text-xs font-bold text-muted-foreground uppercase tracking-wider mb-1.5">Heading</label>
                  <input
                    type="text"
                    value={content.contact.heading}
                    onChange={(e) => updateContact("heading", e.target.value)}
                    className="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground text-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-muted-foreground uppercase tracking-wider mb-1.5">Message</label>
                  <textarea
                    value={content.contact.message}
                    onChange={(e) => updateContact("message", e.target.value)}
                    rows={2}
                    className="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground text-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none resize-y transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-muted-foreground uppercase tracking-wider mb-1.5">Email</label>
                  <input
                    type="email"
                    value={content.contact.email}
                    onChange={(e) => updateContact("email", e.target.value)}
                    placeholder="your@email.com"
                    className="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground text-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-colors"
                  />
                </div>
              </div>
            ) : (
              <>
                <h3 className="text-2xl font-bold text-foreground mb-3">{content.contact.heading}</h3>
                <p className="text-sm text-muted-foreground mb-6 leading-relaxed">
                  {content.contact.message}
                </p>
                {content.contact.email && (
                  <div className="inline-block px-4 py-2 bg-background border border-border rounded-lg text-sm font-semibold text-foreground mb-2">
                    {content.contact.email}
                  </div>
                )}
              </>
            )}
          </div>
          <div className="bg-muted px-6 py-3 flex items-center justify-between border-t border-border">
            <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Contact Section</span>
            <span className="text-xs font-medium text-primary bg-primary/10 px-2 py-1 rounded">Click to {editingSection === "contact" ? "close" : "edit"}</span>
          </div>
        </section>

        {/* Sticky Save Bar */}
        <div className="fixed bottom-0 left-0 right-0 bg-card border-t border-border p-4 z-50 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.05)]">
          <div className="max-w-4xl mx-auto flex items-center justify-between">
            <Link
              href="/dashboard/linkedin/review"
              className="hidden items-center gap-1.5 text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground sm:flex"
            >
              <ArrowLeft className="h-4 w-4" /> Edit profile data
            </Link>

            <button
              onClick={handleSave}
              disabled={saving}
              className="flex items-center justify-center gap-2 rounded-xl bg-primary px-8 py-3 text-sm font-bold text-primary-foreground shadow-[var(--shadow-glow)] transition-all hover:enabled:-translate-y-0.5 hover:enabled:bg-primary-hover disabled:opacity-50 disabled:shadow-none"
            >
              {saving ? <><Loader2 className="h-4 w-4 animate-spin" /> Saving…</> : <>Save &amp; choose template <ArrowRight className="h-4 w-4" /></>}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
